image: minizinc/minizinc:edge

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apk add python3
  - python3 -V               # Print out python version for debugging
  - python3 -m venv venv
  - source venv/bin/activate

test:
  script:
    - pip install tox
    - tox -e check,py37,docs
  artifacts:
    paths: [dist/]
