image: minizinc/minizinc:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .tox/

before_script:
  - apk add python3
  - python3 -V               # Print out python version for debugging
  - python3 -m pip install tox

test:
  script:
    - tox
    - tox -e docs
  artifacts:
    paths: [dist/]
